### ISSUE TITLE
presenterm not respecting config.yaml

### ISSUE THREAD

**Issue by thisismygitrepo** [mfontanini/presenterm#104]
I'm on a linux machine, kitty terminal, and I added a config.yaml @ ~/.config/presenterm

but `presenterm` is not respecting it at all, no matter what I put there.

```yaml


defaults:
  themes: terminal-dark
  footer:
    style: progress_bar

    # Optional!
    character: 🚀

options:
  footer:
    style: progress_bar

    # Optional!
    character: 🚀

```
