### ISSUE TITLE
Leniency flag for cross compatibility

### ISSUE THREAD

**Issue by thisismygitrepo** [mfontanini/presenterm#189]
The program is strict in its parsing (and it should be) but can we have it to be lenient when we explicitly ask for it (e.g. using a flag or config)? 
Usecase: SSH to some machine and there is markdown slides written in one of many other popular tools.

Concretely, I got the following error:
```
invalid presentation metadata: unknown field `marp`, expected one of `title`, `sub_title
`, `author`, `theme`, `options` at line 2 column 1
```

When attempting to read

```
---
marp: true
size: 16:9
layout: cover
invert: true
---

<!-- class: invert -->

# Discharges expected for today using LOS model
Jan 15th 2024

```

I'm would be happy with any behaviour, including rendering as-is, when encountering this, instead of crashing altogether. This would vastly increase the usability of the tool in edge-cases.

Thank you.

**Comment by mfontanini** [comment]
This is fixed in #190. You can now parse that example presentation using a config file like:

```yaml
options:
    strict_front_matter_parsing: false
    # needed so that the `class: invert` command is ignored
    command_prefix: "presenterm:"

```
