### ISSUE TITLE
Is there any way to add support for scaling images?

### ISSUE THREAD

**Issue by mikavilpas** [mfontanini/presenterm#260]
I have a setup with 3 monitors:

```yaml
  Displays:
Colour LCD:
  Display Type:	Built-in Liquid Retina XDR Display
  Resolution:	3456x2234 Retina
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
DELL U2415:
  Resolution:	1200 x 1920
  UI Looks like:	1200 x 1920 @ 60.00Hz
  Mirror:	Off
  Online:	Yes
  Rotation:	90
D32u-40:
  Resolution:	3840x2160 (2160p/4K UHD 1 - Ultra High Definition)
  UI Looks like:	3840 x 2160 @ 60.00Hz
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
```

When creating a presentation for work, I want to include a screenshot of a web page. If I take the screenshot using my DELL U2415 monitor, it will appear about half the size as one taken from the Built-in Liquid Retina XDR Display:

<img width="1727" alt="image" src="https://github.com/mfontanini/presenterm/assets/300791/65cf314c-f712-462c-94a2-2ca283570fb6">
(don't worry about the rest of the presentation, it's still a bit under construction 😄 )

The documentation for presenterm specifies the image should be displayed in its original size, which I think might explain this behaviour.

But I was wondering if there's any way to add support for scaling? Such as
- built in
- using a plugin of some kind (maybe?). There's already functionality that allows executing arbitrary code, so maybe something hacky could be cooked up
- a workaround tip like "to scale images when designing your presentation, you can use `imagemagick ...` and live preview the changes"

What do you think?
