### ISSUE TITLE
Feature request: Hiding code lines in custom snippet executors

### ISSUE THREAD

**Issue by KilianVounckx** [mfontanini/presenterm#313]
It would be nice to have the ability to hide code lines in unsupported languages. I'd imagine this could work by specifying a prefix in the config.yaml file. For example:

```yaml
snippet:
    exec:
        custom:
            c++:
                hide_prefix: "///"
```

c++ is supported of course, but something similar could work in other unsupported languages.
