### ISSUE TITLE
Including Options in a Presentation's Frontmatter Throws an Unrelated Error

### ISSUE THREAD

**Issue by jacksonSingleton** [mfontanini/presenterm#453]
When trying to include the following frontmatter:
```yaml
---
options:
  end_slide_shorthand: true
title: <title>
sub_title: <sub>
author: Jackson Singleton
---
```

or

```yaml
---
title: <title>
sub_title: <sub>
author: Jackson Singleton
options:
  end_slide_shorthand: true
---
```

The following error is returned:

![Image](https://github.com/user-attachments/assets/53c1b992-c6a9-4267-9199-9aae0a07b3cc)

Presentation renders just fine without the existence of the `options` field

Version: `presenterm 0.10.0`
Operating System: `MacOS 15.0`
