### ISSUE TITLE
support for `alignment` command

### ISSUE THREAD

**Issue by JustSimplyKyle** [mfontanini/presenterm#492]
Currently, if you want to horizontally center a text, the only way(I found) is to use custom themed headings as a workaround.
```yaml
h4:
  alignment: center
  colors:
    foreground: "ffffff"
  prefix: ""
  font_size: 1
```
I wish that similar to `font_size`, there exists a command that can alter an element's alignment.
