### ISSUE TITLE
Add theme styling for bold/italic

### ISSUE THREAD

**Issue by bkushigian** [mfontanini/presenterm#501]
I'd like to be able to modify the color/style of bold/italic text. Is it possible to do this?

For instance, I'd like to add the following to a `theme.yaml`:

```yaml
bold:
  colors:
    foreground: palette:yellow
    background: palette:blue_gray
italic:
  colors:
    foreground: palette:red
    background: palette:blue_gray
```
