### ISSUE TITLE
Selected theme is ignored when doing an override

### ISSUE THREAD

**Issue by theseal** [mfontanini/presenterm#548]
When I try to run the following to override of the footer the default theme is selected instead of `terminal-light` as configured.

```
---
title: Awesome title
author: jocar
theme:
  override:
    footer:
      style: template
      right: ""
      left:
        image: ../assets/logo.png
      height: 5
  name: terminal-light
---
```
