### ISSUE TITLE
suggestion: execution_output should have padding

### ISSUE THREAD

**Issue by 0atman** [mfontanini/presenterm#591]
I don't think I can get `execution_output` to have padding, like `code` can have:

```yaml
execution_output:
  padding:
    horizontal: 2
    vertical: 1
```

Note that the code block has padding, but the execution does not, which looks a little mismatched:

![Image](https://github.com/user-attachments/assets/71efb065-9c85-4c74-8459-97187b15063a)

Thanks as ever for making this incredible tool, @mfontanini 😁
