### ISSUE TITLE
[Feature Request] Syntax highlighting for custom snippet executors

### ISSUE THREAD

**Issue by azthec** [mfontanini/presenterm#603]
Thanks for the great tool,

Currently I am working on a presentation where I need to execute python code with a specific command, for example `pytest` or `python -m pytest`, however it seems that once adding a custom snippet I lose all highlighting. So I am forced to choose either between syntax highlighting or code execution.

It is possible to replace the default executor for python, and then both syntax highlighting and code execution is possible, however you then lose the ability to execute code with the default python args.

I would expect a simple property to be available on the executors, such as `syntax: python` or some such.

Looking at the documentation for [custom snippet executors](https://mfontanini.github.io/presenterm/configuration/settings.html#custom-snippet-executors) and [syntax highlighting](https://mfontanini.github.io/presenterm/features/code/highlighting.html#adding-highlighting-syntaxes-for-new-languages) for new languages it would seem that this is not possible.

**Comment by mfontanini** [comment]
Thanks for the report! This makes sense to me, however I'd like to propose an alternative solution: allowing executors.yaml contain alternative executors per language. For example, I imagine a syntax like

```yaml
python:
  filename: snippet.py
  commands:
    - ["python", "-u", "$pwd/snippet.py"]
  alternatives: # needs a better name, uninspired now
    - name: pytest
      commands:
        - ["pytest", "$pwd/snippet.py"]
  hidden_line_prefix: "/// "
```

Then letting you use the alternative executor in your snippet by doing something like:

~~~markdown
```python executor:pytest
<the-code>
````
~~~

Does that work? What you're proposing sounds okay but the main problem is the keys in the executors file are _languages_. So you can't define arbitrary keys there, they all need to exist as a language in the tool. So you can't define `pytest` for example as that's not a language (and making it a language requires changing the code).

**Comment by azthec** [comment]
Yes that's great, it achieves exactly the same end result and it does not seem any less user friendly to me.

An aside, which I think is too small for another issue, it seems that you cannot define alternative executors in your `config.yaml` unless you explicitly add the `exec` property.

I would expect the following to work, so that it keeps compatibility with the -x or -X flag:

```
snippet:
  exec:
    # enable: true # or false
    custom:
      python:
         ....
```
