### ISSUE TITLE
Possible to show date on introduction slide?

### ISSUE THREAD

**Issue by janroden** [mfontanini/presenterm#7]
Thanks for the great app! :)

Is it possible to show a date on the introduction slide defined by the front matter at the beginning of the markdown file:

```yaml
---
title: My presentation title
sub_title: An optional subtitle
author: Your name which will appear somewhere in the bottom
date: 2023-10-18 ???
---
```

Thanks!
