### ISSUE TITLE
Footer changes PDF export accuracy

### ISSUE THREAD

**Issue by Nicceboy** [mfontanini/presenterm#70]
Continuing from the original PDF export issue..

Seems like I figured out the main reason.
I had different footer than in the demo, and that caused "drifting away". I had page numbering on right side. 

Maybe this is endless cat and mice competition, since there can be quite many variations for the footers?

By using progress footer, the accuracy is much better for exporting. Other issues are solved by making terminal larger.

**Comment by mfontanini** [comment]
Hmm weird, even with a custom footer this still works perfect for me. Is there anything crazy about your footer? Are you using emojis? If you could upload a minimal `.md` presentation that reproduces the issues that'd be great.

**Comment by Nicceboy** [comment]
Here is one:

```markdown
---
theme:

  path: theme.yaml

title: Lorem ipsum dolor sit amet
author: Lorem Ipsum 28.11.2023
---

About lorem

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
---

# Lorem Ipsum 

* sunt in culpa qui officia deserunt mollit anim id est laborum.

# Ipsum Amet

<!-- end_slide -->

Dolore Magna?
---

<!-- column_layout: [2, 1] -->
<!-- column: 0 -->

* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

<!-- column: 1 -->


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt. 
<!-- end_slide -->
Lorem ipsum?
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Theme:

```yaml
default:
  margin:
    percent: 5
  colors:
    foreground: "e6e6e6"
    background: "0D1116"


intro_slide:
  title:
    alignment: center
    colors:
      foreground: "b4ccff"
  subtitle:
    alignment: center
    colors:
      foreground: "a5d7e8"
  author:
    alignment: center
    colors:
      foreground: "b6eada"
    positioning: page_bottom


footer:
 style: template
 right: "{current_slide} / {total_slides}"
```
