### ISSUE TITLE
Image color not changing for typst even after changing in config

### ISSUE THREAD

**Issue by mgpinf** [mfontanini/presenterm#96]
Image colour (background and foreground) is not changing even after changing the config file

OS: `MacOS`
Terminal: `Wezterm`

Config file:
```yaml
typst:
  ppi: 300
  colors:
    background: ffffff
    foreground: 000000
```

From the above config, I assume background should be white and foreground should be black.

Image for reference:
<img width="1440" alt="image" src="https://github.com/mfontanini/presenterm/assets/56510798/eed544e7-954e-4e55-85ae-3cf627c251d2">
